name: Some CI

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Check Repo...
      uses: actions/checkout@v5

    - name: Echo something...
      run: |
        echo "Hello"
